---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/random_thoughts":
    get:
      summary: list random_thoughts
      parameters:
      - name: page
        in: query
        description: page number
        required: false
        schema:
          type: integer
      responses:
        '200':
          description: successful
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/paginated_random_thoughts"
    post:
      summary: create random_thought
      parameters: []
      responses:
        '201':
          description: created
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/random_thought_response"
        '400':
          description: bad request
          content:
            application/json:
              examples:
                empty_request:
                  value:
                    status: 400
                    error: bad_request
                    message: param is missing or the value is empty:...
                invalid_request:
                  value:
                    status: 400
                    error: bad_request
                    message: Error occurred while parsing request parameters
              schema:
                "$ref": "#/components/schemas/error"
        '422':
          description: unprocessable entity
          content:
            application/json:
              examples:
                unprocessable_entity:
                  value:
                    status: 422
                    error: unprocessable_entity
                    message: 'Validation failed: Thought can''t be blank, Name can''t
                      be blank'
              schema:
                "$ref": "#/components/schemas/error"
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/create_random_thought"
  "/random_thoughts/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show random_thought
      responses:
        '200':
          description: successful
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/random_thought_response"
        '404':
          description: not found
          content:
            application/json:
              examples:
                not_found:
                  value:
                    status: 404
                    error: not_found
                    message: Couldn't find RandomThought with 'id'=??
              schema:
                "$ref": "#/components/schemas/error"
    patch:
      summary: update random_thought
      parameters: []
      responses:
        '200':
          description: successful
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/random_thought_response"
        '400':
          description: bad request
          content:
            application/json:
              examples:
                empty_request:
                  value:
                    status: 400
                    error: bad_request
                    message: param is missing or the value is empty:...
                invalid_request:
                  value:
                    status: 400
                    error: bad_request
                    message: Error occurred while parsing request parameters
              schema:
                "$ref": "#/components/schemas/error"
        '404':
          description: not found
          content:
            application/json:
              examples:
                not_found:
                  value:
                    status: 404
                    error: not_found
                    message: Couldn't find RandomThought with 'id'=??
              schema:
                "$ref": "#/components/schemas/error"
        '422':
          description: unprocessable entity
          content:
            application/json:
              examples:
                unprocessable_entity:
                  value:
                    status: 422
                    error: unprocessable_entity
                    message: 'Validation failed: Thought can''t be blank, Name can''t
                      be blank'
              schema:
                "$ref": "#/components/schemas/error"
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/update_random_thought"
    delete:
      summary: delete random_thought
      responses:
        '200':
          description: successful
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/random_thought_response"
        '404':
          description: not found
          content:
            application/json:
              examples:
                not_found:
                  value:
                    status: 404
                    error: not_found
                    message: Couldn't find RandomThought with 'id'=??
              schema:
                "$ref": "#/components/schemas/error"
  "/users":
    post:
      summary: create user
      parameters: []
      responses:
        '201':
          description: created
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/user_response"
        '400':
          description: bad request
          content:
            application/json:
              examples:
                empty_request:
                  value:
                    status: 400
                    error: bad_request
                    message: param is missing or the value is empty:...
                invalid_request:
                  value:
                    status: 400
                    error: bad_request
                    message: Error occurred while parsing request parameters
              schema:
                "$ref": "#/components/schemas/error"
        '422':
          description: unprocessable entity
          content:
            application/json:
              examples:
                unprocessable_entity:
                  value:
                    status: 422
                    error: unprocessable_entity
                    message: 'Validation failed: Email can''t be blank, Email must
                      match URI::MailTo::EMAIL_REGEXP, Display name can''t be blank,
                      Password can''t be blank, Password is too short (minimum is
                      8 characters)'
                email_exists:
                  value:
                    status: 422
                    error: unprocessable_entity
                    message: 'Validation failed: Email has already been taken'
              schema:
                "$ref": "#/components/schemas/error"
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/create_user"
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
- url: http://localhost:3000
  description: Local development
components:
  schemas:
    new_random_thought:
      type: object
      properties:
        thought:
          type: string
          minLength: 1
        name:
          type: string
          minLength: 1
      required:
      - thought
      - name
    create_random_thought:
      type: object
      properties:
        random_thought:
          "$ref": "#/components/schemas/new_random_thought"
      required:
      - random_thought
    random_thought_response:
      type: object
      properties:
        id:
          type: integer
        thought:
          type: string
        name:
          type: string
      required:
      - id
      - thought
      - name
    updated_random_thought:
      type: object
      properties:
        thought:
          type: string
          minLength: 1
        name:
          type: string
          minLength: 1
    update_random_thought:
      type: object
      properties:
        random_thought:
          "$ref": "#/components/schemas/updated_random_thought"
      required:
      - random_thought
    paginated_random_thoughts:
      type: object
      properties:
        data:
          type: array
          items:
            "$ref": "#/components/schemas/random_thought_response"
        meta:
          "$ref": "#/components/schemas/pagination"
      required:
      - data
      - meta
    new_user:
      type: object
      properties:
        email:
          type: string
          minLength: 1
          maxLength: 254
        display_name:
          type: string
          minLength: 1
        password:
          type: string
          minLength: 8
        password_confirmation:
          type: string
          minLength: 8
      required:
      - email
      - display_name
      - password
      - password_confirmation
    create_user:
      type: object
      properties:
        user:
          "$ref": "#/components/schemas/new_user"
    user_response:
      type: object
      properties:
        id:
          type: integer
        email:
          type: string
          minLength: 1
          maxLength: 254
        display_name:
          type: string
          minLength: 1
      required:
      - id
      - email
      - display_name
    pagination:
      type: object
      properties:
        current_page:
          type: integer
        next_page:
          type: integer
          nullable: true
        prev_page:
          type: integer
          nullable: true
        total_pages:
          type: integer
        total_count:
          type: integer
      required:
      - current_page
      - next_page
      - prev_page
      - total_pages
      - total_count
    error:
      type: object
      properties:
        status:
          type: integer
        error:
          type: string
        message:
          type: string
      required:
      - status
      - error
      - message
